name: Build VScode for ARM64 v3.1.1

on:
  push:
    paths:
      - arm64_v3.1.1/Dockerfile
      - .github/workflows/arm64_container_build_v3_1_1.yml

env:
  # TODO: Change variable to your image's name
  SOFTWARE: vscode
  VERSION: v3.1.1
  REGISTRY: ghcr.io
  IMAGE_NAME: lescai-teaching/vscode-docker-arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{version}},value=v3.1.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./arm64_v3.1.1/.
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}