channels:
  - conda-forge
  - bioconda

dependencies:
  - bwa=0.7.18
  - bioconda::htslib=1.21
  - bioconda::samtools=1.21
  - bioconda::gatk4=4.6.1.0
  - bioconda::gcnvkernel=0.9
  - bioconda::snpeff=5.3.0a
  - bioconda::snpsift=5.3.0a