channels:
  - conda-forge
  - bioconda

dependencies:
  - bwa=0.7.18
  - bioconda::htslib=1.21
  - bioconda::samtools=1.21
  - bioconda::gatk4=4.6.1.0
  - bioconda::gcnvkernel=0.9
  - bioconda::snpeff=5.2
  - bioconda::snpsift=5.2
  - conda-forge::util-linux
  - conda-forge::python
  - conda-forge::pip
  - conda-forge::jupyterlab=4.2.5
  - conda-forge::ipykernel=6.29.5